version: "3"

services:
  db:
    build:
      context: ./docker/db/
      dockerfile: Dockerfile
      args:
        - BASEOSM_DUMP=${BASEOSM_DUMP}
        - RESTORE_SH=${RESTORE_SH}
    container_name: cne-base
    restart: on-failure
    healthcheck:
      test: "exit 0"
    stdin_open: true
    env_file:
      - '.env'
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
